### ISSUE TITLE
multiline `RUN` at the end of file is broken down

### ISSUE THREAD

**Issue by TomasTomecek** [containerbuildsystem/dockerfile-parse#11] opened 2015-10-02 16:01 UTC
```
RUN yum-config-manager --enable rhel-7-server-rpms || :
RUN yum install -y git tar wget socat hostname sysvinit-tools util-linux yum-utils ethtool&& \
ADD Dockerfile-aos3-aos-base-v3.0.2.900-0 /root/buildinfo/Dockerfile-aos3-aos-base-v3.0.2.900-0
LABEL "Build_Host"="rcm-img-docker01.build.eng.bos.redhat.com"
    yum clean all
RUN rm -f '/etc/yum.repos.d/aos-unsigned.repo'
```

it should be

```
RUN yum-config-manager --enable rhel-7-server-rpms || :
RUN yum install -y git tar wget socat hostname sysvinit-tools util-linux yum-utils ethtool&& \
    yum clean all
RUN rm -f '/etc/yum.repos.d/aos-unsigned.repo'
ADD Dockerfile-aos3-aos-base-v3.0.2.900-0 /root/buildinfo/Dockerfile-aos3-aos-base-v3.0.2.900-0
LABEL "Build_Host"="rcm-img-docker01.build.eng.bos.redhat.com"
```

is this a reactor issue?

**Comment by jpopelka** [comment] 2015-10-02 16:21
How can I reproduce that ?

**Comment by sdodson** [comment] 2015-10-02 17:02
Just use a Dockerfile that ends with a multiline RUN command

```
FROM rhel7:latest
LABEL Component="openshift-enterprise-base-docker"
LABEL Name="aos3/aos-base"
LABEL Version="v3.0.2.900"
LABEL Release="0"
LABEL Architecture="x86_64"
LABEL BZComponent="openshift-enterprise-base-docker"

# components from EPEL must be installed in a separate yum install step
RUN yum-config-manager --enable rhel-7-server-rpms || :
RUN yum install -y git tar wget socat hostname sysvinit-tools util-linux yum-utils ethtool&& \
    yum clean all
```

If I add a blank line and comment to the end of the Dockerfile it works.

**Comment by twaugh** [comment] 2015-10-02 17:47
It's a reactor issue, but might be fixed by https://github.com/projectatomic/atomic-reactor/pull/338.

**Comment by lcarva** [comment] 2021-01-28 14:08
Whatever issue may have existed seems to be fixed now. Using a `Dockerfile` as in previous comment:
```
>>> from dockerfile_parse import DockerfileParser
>>> dfp = DockerfileParser(path='/tmp/Dockerfile')
>>> dfp.structure[-1]
{'instruction': 'RUN', 'startline': 10, 'endline': 11, 'content': 'RUN yum install -y git tar wget socat hostname sysvinit-tools util-linux yum-utils ethtool&& \\\n    yum clean all\n', 'value': 'yum install -y git tar wget socat hostname sysvinit-tools util-linux yum-utils ethtool&&     yum clean all'}
```

**Closed by lcarva** 2021-01-28 14:08 UTC
